
import { Song, BandMember } from './types';

export const BAND_MEMBERS: BandMember[] = [
  {
    id: "aljay",
    name: "Aljay Leodones",
    role: "Founder, Lead Vocals, Lead Guitar, Keyboard",
    photo: "/members/aljay/aljay_profile_pic.jpg",
    extraPhotos: ["/members/aljay/aljay_pic1.jpg", "/members/aljay/aljay_pic2.JPG"],
    bio: "The mastermind who built 3rd Harmonik from the ground up. Aljay channels the stories of friends and loved ones into melodies—sometimes in 10 minutes, sometimes less than 5. With 30+ songs in his arsenal and more brewing, just tell him an inspiring story and watch a new track appear.",
    height: "5'8\"",
    favoriteSong: "Kometa"
  },
  {
    id: "louie",
    name: "Louie",
    role: "Drums",
    photo: "/members/louie/louie_profile_pic.jpg",
    extraPhotos: ["/members/louie/louie_pic1.jpg", "/members/louie/louie_pic2.jpg"],
    bio: "Aljay's ride-or-die for over 12 years. What started as desk neighbors in class evolved into an unbreakable musical brotherhood. Louie's drumming is the heartbeat that gives every 3rd Harmonik track its unique pulse and flavor.",
    height: "5'5\"",
    favoriteSong: "Titulo"
  },
  {
    id: "anthony",
    name: "Anthony",
    role: "Lead Vocals, Bass Guitar",
    photo: "/members/anthony/anthony_profile_pic.JPG",
    extraPhotos: ["/members/anthony/anthony_pic1.JPG", "/members/anthony/anthony_pic2.JPG"],
    bio: "The low-end powerhouse with vocals that hit different. Anthony doesn't just play bass—he co-writes fire tracks with Aljay. Their first collab 'Lihim' sealed the deal and brought a whole new dimension to the band's sound.",
    height: "5'7\"",
    favoriteSong: "How Could You"
  },
  {
    id: "clyde",
    name: "Clyde",
    role: "Lead Vocals, Rhythm Guitar",
    photo: "/members/clyde/clyde_profile_pic.gif",
    extraPhotos: ["/members/clyde/clyde_pic1.JPG", "/members/clyde/clyde_pic2.JPG"],
    bio: "The voice that completes 3rd Harmonik's identity. With Clyde's powerful vocals in the mix, Aljay finally had the freedom to write melodies without limits. That's why the songs keep coming faster than ever.",
    height: "5'7\"",
    favoriteSong: "How Could You"
  }
];

const COLORS = ['#ec4899', '#6366f1', '#f59e0b', '#10b981', '#ef4444', '#8b5cf6'];

export const SONGS_VERSION = 'v11';

// Define custom song order - songs not in this list will appear after in their original order
const SONG_ORDER = [
  'obvious',
  'how-could-you',
  'kometa',
  'titulo',
  'nandito',
  'aking-prinsesa',
  'babalik',
  'bulong',
  'cold',
  'gamba',
  'guni-guni',
  'hello-heartache',
  'huling-sandali',
  'i-guess-well-never-know',
  'jopay',
  'kailan-sinta',
  'love',
  'makulimlim',
  'my-beautiful-disaster',
  'nobody-knows',
  'pagtatapos',
  'pahina',
  'perfect-time',
  'sa-ngalan-ng-pagibig',
  'totoo',
  'undo'
];

const _UNSORTED_SONGS: Song[] = [
  {
    id: "aking-prinsesa",
    title: "Aking Prinsesa",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "/music/Aking Prinsesa/COVER - Aking Prinsesa.png",
    url: "/music/Aking Prinsesa/Aking Prinsesa - 3rd Harmonik.mp3",
    duration: "4:02",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ec4899",
    funFacts: ["Inspired by the feeling of reaching for something unreachable, like a 'suntok sa buwan'.", "Reflects the theme of a 'soldier' guarding a princess he can't touch.", "Focuses on the beauty of a dream vs. the reality of distance."],
    lyrics: [
      "Aking Prinsesa - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Isang hindi mapaliwanag,",
      "Na nararamdaman,",
      "Gusto kong lumapit,",
      "Pero suntok sa buwan,",
      "Hindi kapani-paniwala,",
      "Ang iyong kagandahan,",
      "Oh, aking prinsesa,",
      "Na hindi ko mahawakan,",
      "",
      "[Refrain]",
      "Biglang bumagal,",
      "Ang oras at musika,",
      "Nung ika'y makita,",
      "Parang nasa pelikula..",
      "",
      "[Chorus]",
      "Oh, aking prinsesa,",
      "Tayo'y magkabilang mundo,",
      "Isang hamak na sundalo mo,",
      "Sa isang ubod ng ganda,",
      "Oh, kay sigla,",
      "Ng gabi at kay tahimik,",
      "Siguro nga, wala akong marinig,",
      "At ako'y nana-naginip nalang,",
      "Oh, aking prinsesa,",
      "Sa panaginip nalang..",
      "",
      "[Verse 2]",
      "Ako'y hindi mapakali,",
      "Na tila ba nagmamadali,",
      "Gusto kong maka-usap ka,",
      "Pero sadyang imposible,",
      "Hindi ako makalapit,",
      "Lumalayo ang daan,",
      "Oh, aking prinsesa,",
      "Gusto kitang mahawakan,",
      "",
      "[Refrain]",
      "Biglang bumagal,",
      "Ang oras at musika,",
      "Nung ika'y lumingon,",
      "Parang ako'y babangon..",
      "",
      "[Chorus]",
      "Oh, aking prinsesa,",
      "Tayo'y magkabilang mundo,",
      "Isang hamak na sundalo mo,",
      "Sa isang ubod ng ganda,",
      "Oh, kay sigla,",
      "Ng gabi at kay tahimik,",
      "Siguro nga, wala akong marinig,",
      "At ako'y nana-naginip nalang,",
      "Oh, aking prinsesa,",
      "Sa panaginip nalang..",
      "",
      "Mmmm.. aking prinsesa..",
      "Ohhh.. prinsesa..",
      "Aking prinsesa,",
      "Ikaw nag-i-isa..",
      "",
      "[Chorus]",
      "Oh, aking prinsesa,",
      "Tayo'y magkabilang mundo,",
      "Isang hamak na sundalo mo,",
      "Sa isang ubod ng ganda,",
      "Oh, kay sigla,",
      "Ng gabi at kay tahimik,",
      "Siguro nga, wala akong marinig,",
      "At ako'y nana-naginip nalang,",
      "Oh, aking prinsesa,",
      "Sa panaginip nalang..",
      "",
      "[Chorus]",
      "Oh, aking prinsesa,",
      "Tayo'y magkabilang mundo,",
      "Isang hamak na sundalo mo,",
      "Sa isang ubod ng ganda,",
      "Oh, kay sigla,",
      "Ng gabi at kay tahimik,",
      "Siguro nga, wala akong marinig,",
      "At ako'y nana-naginip nalang,",
      "Oh, aking prinsesa,",
      "Sa panaginip nalang..",
      "",
      "Mmmm.. aking prinsesa..",
      "Ohhh.. prinsesa..",
      "Ohhh.. prinsesa.. ohhhh",
      "Aking prinsesa.. ohhh"
    ]
  },
  {
    id: "how-could-you",
    title: "How Could You",
    artist: "3rd Harmonik",
    album: "The Broken Trust Anthology",
    cover: "/music/How Could You/COVER - How Could You.png",
    url: "/music/How Could You/How Could You - 3rd Harmonik.mp3",
    duration: "3:58",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ef4444",
    funFacts: [
      "Written in just 10 minutes to channel a storm of raw emotion.",
      "Sparked by Clyde's painful recounting of a past relationship.",
      "The word 'peace' in the chorus also implies a shattered 'piece' of the soul."
    ],
    lyrics: [
      "[Verse]",
      "How could you?",
      "Split my heart in two,",
      "How could you,",
      "Have made yourself weak,",
      "Now I'm turnin' into,",
      "Something I'm not,",
      "So you mean that,",
      "You made me believe,",
      "That you were weak,",
      "The entire time.. ohh..",
      "",
      "Honestly, I cared for you,",
      "Actually, you know it's true,",
      "That deep down this darkness,",
      "It's brighten up by you,",
      "",
      "[Chorus]",
      "You taught me how to understand,",
      "Now, you shattered my peace,",
      "I can't hate  you now,",
      "Would you tell me how?",
      "How could you, my love?",
      "How could you.... ohh...",
      "",
      "[Verse]",
      "I don't believe you,",
      "I know that's not it,",
      "Why won't you say something?",
      "How could you,",
      "Have made yourself weak,",
      "The entire time,",
      "Made me believe,",
      "That there could be something,",
      "But what is this feeling? Ohh..",
      "",
      "Honestly, I cared for you,",
      "Actually, you know it's true,",
      "That deep down this darkness,",
      "It's brighten up by you,",
      "",
      "[Chorus]",
      "You taught me how to understand,",
      "Now, you shattered my peace,",
      "I can't hate you now,",
      "Would you tell me how?",
      "How could you, my love?",
      "How could you.... ohh...",
      "",
      "[Bridge]",
      "How could you, my love?",
      "How could you.... ohh...",
      "How could you, my love?",
      "How could you.... ohh...",
      "",
      "[Chorus]",
      "You taught me how to understand,",
      "Now, you shattered my peace,",
      "I can't hate you now,",
      "Would you tell me how?",
      "How could you, my love?",
      "How could you.... ohh...",
      "",
      "How could you, my love?",
      "",
      "[Final]",
      "How could you, my love?",
      "How could you.... ohh...",
      "How could you, my love?",
      "How could you.... ohh...",
      "How could you, my love?",
      "How could you.... ohh...",
      "How could you, my love?",
      "How could you.... ohh..."
    ]
  },
  {
    id: "obvious",
    title: "Obvious",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "/music/Obvious/COVER - Obvious.png",
    url: "/music/Obvious/Obvious - 3rd Harmonik.mp3",
    duration: "4:20",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ec4899",
    funFacts: [
      "Inspired by a lightning-in-a-bottle melody during a college afternoon.",
      "Captures the intoxicating realization of a favorite voice.",
      "The bridge acts as an introvert's brave moment of confession."
    ],
    lyrics: [
      "[Verse]",
      "Can we talk,",
      "for a little more while?",
      "I can't get enough of it,",
      "your voice, your smile,",
      "Think I'm addicted,",
      "it's so complicated,",
      "Getting disoriented,",
      "It's at the tip,",
      "of my tongue,",
      "But I can't let it out..",
      "",
      "How long do I have to,",
      "Hide this feeling,",
      "This obvious grinning,",
      "I'm still believing..",
      "",
      "[Chorus]",
      "I'm sorry 'coz I love you now,",
      "Can't quite figure it out,",
      "How to show you,",
      "How to say it, how to prove it,",
      "I'm sorry I have to tell you,",
      "This hopeless feeling,",
      "That I am clinging,",
      "To a dying hope,",
      "I pray.. that you would say..",
      "",
      "[Verse]",
      "Can we walk,",
      "for a little more while?",
      "I can't get enough of it,",
      "your scent, your style,",
      "Think I'm addicted,",
      "it's so complicated,",
      "Getting disoriented,",
      "It's at the tip,",
      "of my tongue,",
      "But I can't let it out..",
      "",
      "How long do I have to,",
      "Hide this feeling,",
      "This obvious grinning,",
      "I'm still believing..",
      "",
      "[Chorus]",
      "I'm sorry 'coz I love you now,",
      "Can't quite figure it out,",
      "How to show you,",
      "How to say it, how to prove it,",
      "I'm sorry I have to tell you,",
      "This hopeless feeling,",
      "That I am clinging,",
      "To a dying hope,",
      "I pray.. that you would say..",
      "",
      "[Bridge]",
      "It's obvious, I know,",
      "But I want to show,",
      "I can't lie low,",
      "This is embarrassing,",
      "But I'm getting,",
      "The feeling,",
      "That you somehow smiled,",
      "Is it obvious?",
      "Obvious..",
      "",
      "[Chorus]",
      "I'm sorry 'coz I love you now,",
      "Can't quite figure it out,",
      "How to show you,",
      "How to say it, how to prove it,",
      "I'm sorry 'coz I loved you now,",
      "Can't quite figure it how,",
      "How to show you,",
      "How to say it, how to prove it,",
      "I'm sorry I have to tell you,",
      "This hopeless feeling,",
      "That I am clinging,",
      "To a dying hope,",
      "I pray.. that you would say..",
      "",
      "Is it obvious?",
      "Obvious..",
      "Is it obvious?",
      "Obvious..",
      "Is it obvious?",
      "Obvious..",
      "Is it obvious?",
      "Obvious.."
    ]
  },
  {
    id: "babalik",
    title: "Babalik",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "/music/Babalik/COVER - Babalik.png",
    url: "/music/Babalik/Babalik - 3rd Harmonik.mp3",
    duration: "3:45",
    playCount: 0,
    isFavorite: false,
    accentColor: "#6366f1",
    funFacts: ["A song about inevitable return and destiny.", "Uses the metaphor of a firefly as a guide in the sky.", "Expresses that even if worlds change, paths will still meet."],
    lyrics: [
      "[Verse 1]",
      "Sa himpapawid, tinititigan kita,",
      "Tila isang alitaptap, aking gabay,",
      "Sa dulo ng mundo ay, ako maghihintay,",
      "Sa bawat pag-ulit ng kalangitan, hindi ka bibitawan.",
      "",
      "Kung naalala mo ang mga istorya ko,",
      "Isa lang ang direksyon, yun ang punto,",
      "Hindi kakalimutan, mga leksyon,",
      "Nasa iyo parati ang aking atensyon.",
      "",
      "[Refrain]",
      "Kahit anong agwat, kahit anong hadlang,",
      "Hinding hindi mapipigilan,",
      "",
      "[Chorus]",
      "Hindi ko man masabi sa'yo,",
      "Maghahanap din ng paraan ang mundo,",
      "Kaya't babalik at babalik din ako,",
      "Upang siguraduhin ang ating kwento,",
      "Sa'yo, sa'yo, makokontento,",
      "Isang estoryang nakasulat sa aklat kong nakatago, tapos,",
      "Sa'yo ang simula. Sa'yo din magtatapos.",
      "",
      "Sa buong buhay ko,",
      "Halos libong kwento maririnig,",
      "Ikaw ang paborito.",
      "",
      "[Verse 2]",
      "Minsan kapag nakatulala,",
      "Hindi mapalagay ang aking isipan,",
      "Alam ng puso kong nasa likoran, ka ng pinto na, namamagitan sa, ikaw at ako,",
      "Umaasa lang naman, na masilayan ka lang, at makausap ka,",
      "Umaasa lang naman. Sa ngayon, sa panaginip nalang..",
      "",
      "[Refrain]",
      "Kahit anong agwat, kahit anong hadlang,",
      "Hinding hindi mapipigilan,",
      "",
      "[Chorus]",
      "Hindi ko man masabi sa'yo,",
      "Maghahanap din ng paraan ang mundo,",
      "Kaya't babalik at babalik din ako,",
      "Upang siguraduhin ang ating kwento,",
      "Sa'yo, sa'yo, makokontento,",
      "Isang estoryang nakasulat sa aklat kong nakatago, tapos,",
      "Sa'yo ang simula. Sa'yo din magtatapos.",
      "",
      "Sa buong buhay ko,",
      "Halos libong kwento maririnig,",
      "Ikaw ang paborito.",
      "",
      "[Bridge]",
      "Sa ibang mundo man tayo magising,",
      "Sa bagong daigdig na hindi atin,",
      "Magtatagpo, at magtatagpo rin,",
      "Nakaukit na sa bato, nakatatak na sa ating kwento",
      "",
      "[Chorus]",
      "Hindi ko man masabi sa'yo,",
      "Maghahanap din ng paraan ang mundo,",
      "Kaya't babalik at babalik din ako,",
      "Upang siguraduhin ang ating kwento,",
      "Sa'yo, sa'yo, makokontento,",
      "Isang estoryang nakasulat sa aklat kong nakatago, tapos,",
      "Sa'yo ang simula. Sa'yo din magtatapos.",
      "",
      "Sa buong buhay mo,",
      "Halos libong kwento maririnig,",
      "Ikaw ang paborito.",
      "",
      "Hindi ko man masabi sa'yo..",
      "Babalik at babalik din ako,",
      "Hindi ko man masabi sa'yo..",
      "Babalik at babalik din ako,"
    ]
  },
  {
    id: "bulong",
    title: "Bulong",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "/music/Bulong/COVER - Bulong.png",
    url: "/music/Bulong/Bulong - 3rd Harmonik.mp3",
    duration: "3:12",
    playCount: 0,
    isFavorite: false,
    accentColor: "#10b981",
    funFacts: ["Captures the nervousness of being unable to speak feelings aloud.", "Describes being an 'alipin ng pag-ibig' (slave to love).", "The title refers to whispering to the side when words fail."],
    lyrics: [
      "Hindi masabi ang nararamdaman",
      "Di makalapit sadyang nanginginig na lang",
      "Mga kamay na sabik sa piling mo",
      "Ang iyong matang walang mintis sa pagtigil ng aking mundo",
      "",
      "Ako'y alipin ng pagibig mo",
      "Handang ibigin ang isang tulad mo",
      "Hanggat ang puso mo'y sa akin lang hindi ka na malilinlang",
      "Ikaw ang ilaw sa dilim at ang liwanag ng mga bituin",
      "",
      "Hindi mapakali",
      "Hanggang tingin nalang",
      "Bumubulong sa'yong tabi",
      "Sadyang walang makapantay",
      "Sa kagandahang inuukit mo sa isip ko",
      "",
      "Ako'y alipin ng pagibig mo",
      "Handang ibigin ang isang tulad mo",
      "Hanggat ang puso mo'y sa akin lang hindi ka na malilinlang",
      "Ikaw ang ilaw sa dilim at ang liwanag ng mga bituin",
      "",
      "Oh woah",
      "Oh woah",
      "",
      "Ako'y alipin ng pagibig mo (alipin ng pagibig mo)",
      "Handang ibigin ang isang tulad mo (ibigin ang isang tulad mo)",
      "Hanggat ang puso mo'y sa akin lang hindi ka na malilinlang",
      "Ikaw ang ilaw sa dilim at ang liwanag ng mga bituin",
      "",
      "Ng mga bituin",
      "Ng mga bituin",
      "Ng mga bituin"
    ]
  },
  {
    id: "cold",
    title: "Cold",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Cold/Cold - 3rd Harmonik.mp3",
    duration: "3:55",
    playCount: 0,
    isFavorite: false,
    accentColor: "#6366f1",
    funFacts: ["Written about sacrifices made during sleepless nights and endless days.", "The 'main stage' represents the breakthrough after the struggle.", "A tribute to everyone who makes the hard work worthwhile."],
    lyrics: [
      "Cold - 3rd Harmonik",
      "",
      "[Verse]",
      "The cold came earlier,",
      "We didn't expect that,",
      "I was very close, that I could never forget,",
      "The sacrifices that we have made,",
      "The sleepless nights and the endless days,",
      "You make it worthwhile,",
      "Ohhh..",
      "",
      "[Chorus]",
      "The world is unfair,",
      "There's more to bare..",
      "Please, don't let it go,",
      "You don't let it show,",
      "That's the hard part,",
      "Ohh, that's the hard part,",
      "I swear everything will change,",
      "Because this is our main stage,",
      "Oh, this is our, this is our main stage..",
      "",
      "[Verse 2]",
      "Now the show starts,",
      "Didn't forget that,",
      "We were so close,",
      "Wish you'd remember,",
      "The sacrifices,",
      "That we have made,",
      "The rainy nights and,",
      "The endless sun,",
      "You make it worthwhile,",
      "Ohhh..",
      "",
      "[Chorus]",
      "The world is unfair,",
      "There's more to bare..",
      "Please, don't let it go,",
      "You don't let it show,",
      "That's the hard part,",
      "Ohh, that's the hard part,",
      "I swear everything will change,",
      "Because this is our main stage,",
      "Oh, this is our, this is our main stage..",
      "",
      "[Verse 3]",
      "Now that we're in the lights,",
      "Don't stop the show,",
      "Don't let the cold come,",
      "'Coz we were just,",
      "Just getting hot,",
      "Wish you'd never stop,",
      "'Coz You make it worthwhile,",
      "Ohhh..",
      "",
      "[Chorus]",
      "The world is unfair,",
      "There's more to bare..",
      "Please, don't let it go,",
      "You don't let it show,",
      "That's the hard part,",
      "Ohh, that's the hard part,",
      "I swear everything will change,",
      "Because this is our main stage,",
      "Oh, this is our, this is our main stage..",
      "",
      "This is our main stage,",
      "Oh, this is our, this is our main stage..",
      "Yeah.. ohhh...",
      "",
      "[Final]",
      "The world's so unfair,",
      "No more left to bare..",
      "Please, don't let me go,",
      "You don't let it show,",
      "That's the hard part,",
      "Ohh, that's the hard part,",
      "I swear everything can change,",
      "Because this is our main stage,",
      "Oh, this is our, this is our main stage..",
      "Ohhh.. our main stage..",
      "Ohh.. This is our, this is our main stage.."
    ]
  },
  {
    id: "gamba",
    title: "Gamba",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Gamba/Gamba - 3rd Harmonik.mp3",
    duration: "4:05",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ef4444",
    funFacts: ["Modern lyrics referencing DMs, block lists, and Spotify loops.", "Uses the 'expiry date' of a telco promo as a metaphor for love.", "A relatable track for the digital age of heartbreak."],
    lyrics: [
      "[Verse 1]",
      "Oh.. ako’y nangangamba,",
      "Tila ba walang oras nang natitira,",
      "At patuloy kang nahuhulog sa piling ng iba.",
      "Hindi ko hangad na maging kontrabida,",
      "Pero ‘yang ngiti mo sa kanya parang bala sa dibdib ko, sumasabog sa ribla,",
      "Parang “kontrabando” ‘yang pag-ibig mo,",
      "Pinusuan mo ‘ko noon, pero pinipilit na ngayon.",
      "",
      "Parang sinasadya mo ‘yung mga post na sweet sa timeline,",
      "Para masaksihan ko pa kung paano ka sumaya sa ibang lalaki.",
      "Sabi mo “friends lang,” pero ‘yang mga heart eyes mo hindi na friendly,",
      "Parang double-tap na nagiging dagger sa lalamunan ko, hindi na healthy.",
      "Ako ‘yung tipong tahimik lang, pero sa loob nagwawala,",
      "",
      "[Hook]",
      "Sabi mo “forever” pero parang promo lang ng telco,",
      "May expiry date, may limit, may “sorry naubusan na ng lod mo.”",
      "Ako pa rin ‘to, ‘di nagbago,",
      "Pero ikaw na yata ‘yung nag-upgrade—sa iba.",
      "",
      "[Verse 2]",
      "Seen mo lang ang text, walang reply ah,",
      "Parang jeep sa EDSA, puno na, ‘di na makasingit pa",
      "Sabi nila “move on” daw, ‘di worth it ‘yung luha,",
      "Pero ‘pag gabi, ikaw pa rin ang autoplay sa utak ko parang Spotify na walang skip ad pa.",
      "Multo mo sa DMs, hindi nag-ghost,",
      "Pero sa totoong buhay, parang spam account—blocked, ayaw nang mag-post.",
      "Alam ko mali ‘yung pag-asa, parang overtime sa trabaho na walang bayad pa,",
      "Pero kahit lugmok, ayaw ko pang mag-sign out sa kwento nating dal’wa.",
      "",
      "[Hook]",
      "Sabi mo “forever” pero parang promo lang ng telco,",
      "May expiry date, may limit, may “sorry naubusan na ng load mo.”",
      "Ako pa rin ‘to, ‘di nagbago,",
      "Pero ikaw na yata ‘yung nag-upgrade—sa iba, sa iba.",
      "",
      "[Bridge]",
      "Siguro kaya ganito kasi ‘di ako sanay mag-let go,",
      "Parang laging “one more episode” sa series na alam kong masakit na ang ending pero pinipilit ko pa rin panoorin hanggang credits roll.",
      "Kung sakali mang magkabalikan,",
      "‘Wag mo nang ulitin ‘yung pag-alis—",
      "Kasi ‘pag umalis ka ulit, baka ‘di na ‘ko ‘yung dating ako na handa pang maghabol kahit umuulan ng bato.",
      "",
      "[Hook]",
      "Sabi mo “forever” pero parang promo lang ng telco,",
      "May expiry date, may limit, may “sorry naubusan na ng load mo.”",
      "Ako pa rin ‘to, ‘di nagbago,",
      "Pero ikaw na yata ‘yung nag-upgrade—sa iba, sa iba.",
      "",
      "[Hook]",
      "Sabi mo “forever” pero parang promo lang ng telco,",
      "May expiry date, may limit, may “sorry naubusan na ng load mo.”",
      "Ako pa rin ‘to, ‘di nagbago,",
      "Pero ikaw na yata ‘yung nag-upgrade—sa iba, sa iba."
    ]
  },
  {
    id: "guni-guni",
    title: "Guni-Guni",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Guni-Guni/Guni-Guni - 3rd Harmonik.mp3",
    duration: "3:48",
    playCount: 0,
    isFavorite: false,
    accentColor: "#8b5cf6",
    funFacts: ["Explores the hallucinations and overthinking that come with infatuation.", "The title means 'illusion' or 'hallucination'.", "Captures the bridge between dreams and reality."],
    lyrics: [
      "Guni-guni - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Gusto kong malaman,",
      "Laman ng isip mo,",
      "Ano ba kaya, 'di mabibigla,",
      "Biglang nabahala,",
      "Ako ba kaya'y napansin? Oh eto'y halik nalang sa hangin?",
      "Pwede bang 'wag mong sabihin?",
      "Sabihin ang 'di ko gustong marinig,",
      "Subalit teka lang, sige nalang,",
      "Ibato mo na sa akin",
      "",
      "Gustong magkunwari,",
      "Na wala kong paki,",
      "Gusto ko lang naman masabi mo, na ako'y madaling kausap,",
      "Pero sige na, tatanggapin ko na",
      "",
      "[Refrain]",
      "Ang akin lang naman,",
      "Ay iyong mapagbigyan",
      "",
      "[Chorus]",
      "Oh, bini-bini kong,",
      "Kay tamis ng ngiti,",
      "Para bang kailan lang, kailan lang kitang nasilayan,",
      "Kay bilis ng panahon,",
      "Para bang akoy dinadala, dinadala ng mga,",
      "Sobra kong pag-iisip, 'di sa pagpapantasya,",
      "Kundi sobra kong hanga sa'yo, pwede bang,",
      "Masilayan ka ulit? Nang mahimbing ang tulog ko, ohh..",
      "Isa na namang guni-guni,",
      "Isa na namang guni-guni,",
      "",
      "[Verse 2]",
      "Gusto kong malaman,",
      "Kung saan patungo,",
      "Saan ba kaya, 'di mabibigla,",
      "Biglang naliligaw,",
      "Ako na ba'y babangon na? Oh eto'y puro lang salita?",
      "Pwede bang 'wag iisipin?",
      "Ang gulo gulo ng isipan,",
      "Teka lang, sige nalang,",
      "Ibato mo na sa akin",
      "",
      "[Refrain]",
      "Ang akin lang naman,",
      "Ay iyong mapagbigyan",
      "",
      "[Chorus]",
      "Oh, bini-bini kong,",
      "Kay tamis ng ngiti,",
      "Para bang kailan lang, kailan lang kitang nasilayan,",
      "Kay bilis ng panahon,",
      "Para bang akoy dinadala, dinadala ng mga,",
      "Sobra kong pag-iisip, 'di sa pagpapantasya,",
      "Kundi sobra kong hanga sa'yo, pwede bang,",
      "Masilayan ka ulit? Nang mahimbing ang tulog ko, ohh..",
      "Isa na namang guni-guni,",
      "Isa na namang guni-guni,",
      "",
      "[Bridge]",
      "Ah.. ayan na naman ako,",
      "Pero sasabihin ko na sa'yo,",
      "Para itong guni-guni ko'y mabu-buo,",
      "Magkaka-totoo rin ito..",
      "",
      "[Final]",
      "Oh, bini-bini kong,",
      "Kay tamis ng ngiti,",
      "Para bang kailan lang, kailan lang kitang nasilayan,",
      "Kay bilis ng panahon,",
      "Para bang akoy dinadala, dinadala ng mga,",
      "Sobra kong pag-iisip, 'di sa pagpapantasya,",
      "Kundi sobra kong hanga sa'yo, pwede bang,",
      "Masilayan ka ulit? Nang mahimbing ang tulog ko, ohh..",
      "Isa na namang guni-guni,",
      "Isa na namang guni-guni,",
      "Isa na namang guni-guni,",
      "Isa na namang guni-guni,"
    ]
  },
  {
    id: "hello-heartache",
    title: "Hello, Heartache!",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Hello, Heartache!/Hello, Heartache! - 3rd Harmonik.mp3",
    duration: "4:30",
    playCount: 0,
    isFavorite: false,
    accentColor: "#f59e0b",
    funFacts: ["A greeting to the familiar pain of unrequited love.", "Features lyrics about watching from afar and being 'drawn to your essence'.", "The bridge asks whether to find courage or let the feelings grow silently."],
    lyrics: [
      "Hello, Heartache! - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Watching from afar,",
      "It's hard to believe,",
      "Your beauty's so vivid,",
      "It's like a dream,",
      "I'm drawn to your essence,",
      "So effortlessly,",
      "Pardon my gaze,",
      "But you're all that I see,",
      "",
      "Your laughter’s like music,",
      "It plays in my mind,",
      "A tune so flawless,",
      "It's one of a kind,",
      "Your smile lights the room,",
      "In a way so fine,",
      "Enthralled by your presence,",
      "In every single line,",
      "",
      "[Refrain]",
      "You're always on my mind, ohh...",
      "I can't think clearly...",
      "",
      "[Chorus]",
      "Hello, heartache!",
      "It's me once more,",
      "Wishing this time,",
      "She’d notice me,",
      "Oh, the irony!",
      "I feel I might break,",
      "If she looks my way,",
      "I might just fade,",
      "Hello, heartache!",
      "It's you again,",
      "Wishing this time,",
      "It will never end,",
      "Forgive me but, I must turn away,",
      "Damn... damn... guess I have to turn away,",
      "",
      "[Verse 2]",
      "Every step you take,",
      "Is like a dance so sweet,",
      "Your grace and charm,",
      "Make my heart skip a beat,",
      "Your eyes like stars,",
      "In a sky so deep,",
      "I get lost in their shine,",
      "And I don't even mind,",
      "",
      "The way you brush your hair,",
      "Behind your ear so neat,",
      "Makes my heart race,",
      "Every time we meet,",
      "Your voice is a whisper,",
      "In a gentle breeze,",
      "It soothes my restless soul,",
      "And puts my mind at ease,",
      "",
      "[Refrain]",
      "You're always on my mind, ohh...",
      "I can't think clearly...",
      "",
      "[Chorus]",
      "Hello, heartache!",
      "It's me once more,",
      "Wishing this time,",
      "She’d notice me,",
      "Oh, the irony!",
      "I feel I might break,",
      "If she looks my way,",
      "I might just fade,",
      "Hello, heartache!",
      "It's you again,",
      "Wishing this time,",
      "It will never end,",
      "Forgive me but, I must turn away,",
      "Damn... damn... guess I have to turn away,",
      "",
      "[Bridge]",
      "Will I find the courage,",
      "To let you know?",
      "Or am I bound,",
      "To let these feelings grow?",
      "In this world of light,",
      "Where hope feels strong,",
      "I keep believing,",
      "That with you I belong,",
      "",
      "[Refrain]",
      "You're always on my mind, ohh...",
      "I can't think clearly...",
      "",
      "[Chorus]",
      "Hello, heartache!",
      "It's me once more,",
      "Wishing this time,",
      "She’d notice me,",
      "Oh, the irony!",
      "I feel I might break,",
      "If she looks my way,",
      "I might just fade,",
      "",
      "[Final]",
      "Hello, heartache!",
      "It's me once more,",
      "Wishing this time,",
      "She’d notice me,",
      "Oh, the irony!",
      "I feel I might break,",
      "If she looks my way,",
      "I might just fade,",
      "Hello, heartache!",
      "It's you again,",
      "Wishing this time,",
      "It will never end,",
      "Forgive me but, I must turn away,",
      "Damn... damn... guess I have to turn away,",
      "",
      "[Outro]",
      "Watching from afar,",
      "It's hard to believe,",
      "Your beauty's so vivid,",
      "It's like a dream,",
      "I'm drawn to your essence,",
      "So effortlessly,",
      "Pardon my gaze,",
      "But you're all that I see.."
    ]
  },
  {
    id: "huling-sandali",
    title: "Huling Sandali",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "/music/Huling Sandali/Huling Sandali (Cover) - 3rd Harmonik.png",
    url: "/music/Huling Sandali/Huling Sandali (Cover) - 3rd Harmonik.mp3",
    duration: "4:10",
    playCount: 0,
    isFavorite: false,
    accentColor: "#8b5cf6",
    funFacts: ["A song about making the last moment count.", "Reflects on the pain of memories that won't fade.", "The bridge is a plea for one last chance at love."],
    lyrics: [
      "[Verse 1]",
      "Hindi mapigil ang bugso ng aking puso",
      "Sa t'wing ako’y papalapit sa'yo",
      "Maaari bang hingin ang iyong kamay?",
      "Hawakan mo't ’wag mong bitawan",
      "",
      "[Verse 2]",
      "Hindi mapigil ang tibok ng aking puso",
      "Sa t'wing ako'y nakatingin sa'yo",
      "Maaari bang 'wag kang humiwalay?",
      "Dahil sandali na lang",
      "",
      "[Pre-Chorus]",
      "Darating din ang gabing walang pipigil sa'tin",
      "Kung hindi ngayon, aasa bang maibabalik ang kahapon?",
      "",
      "[Chorus]",
      "Kahit sandali",
      "Palayain ang pusong 'di mapigil",
      "Sana'y tayong dalawa sa huling pagkakataon",
      "Na ika’y magiging akin",
      "",
      "[Verse 3]",
      "Hindi matigil ang gulo sa aking isip",
      "At para bang walang kasing sakit",
      "Alaala mong hindi ko malimutan",
      "Oras lang ang may alam",
      "",
      "[Pre-Chorus]",
      "Kung darating din ang gabing walang pipigil sa’tin",
      "Kung hindi ngayon, aasa bang maibabalik ang kahapon?",
      "",
      "[Chorus]",
      "Kahit sandali",
      "Palayain ang pusong 'di mapigil",
      "Sana’y tayong dalawa sa huling pagkakataon",
      "Na hindi na para sa'tin",
      "",
      "[Bridge]",
      "At sa bawat minuto, ako'y 'di natuto",
      "Ipilit mang iba, ako’y maghihintay sa'yo",
      "Ikaw ang aking kapiling sa huling sandali",
      "Kasalanan ba kung puso natin ang magwawagi?",
      "",
      "[Chorus]",
      "Kahit sandali",
      "Palayain ang pusong 'di mapigil",
      "Sana'y tayong dalawa sa huling pagkakataon",
      "Na hindi na para sa'tin",
      "",
      "[Outro]",
      "Kahit sandali",
      "Patawarin ang pusong 'di tumigil",
      "Para sa'ting dalawa ang maling pagkakataon",
      "Na ika'y magiging akin"
    ]
  },
  {
    id: "i-guess-well-never-know",
    title: "I Guess We'll Never Know",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/I Guess We'll Never Know/I Guess We'll Never Know - 3rd Harmonik.mp3",
    duration: "4:45",
    playCount: 0,
    isFavorite: false,
    accentColor: "#6366f1",
    funFacts: ["A melancholic reflection on a relationship that ended without closure.", "Features a beautiful 'La, la, la' hook.", "The lyrics delve into the 'misery' of not knowing what could have been."],
    lyrics: [
      "[Hook]",
      "La, la, la..",
      "La, la, la..",
      "La, la, la..",
      "La, la, la..",
      "",
      "[Verse 1]",
      "I'm sorry when,",
      "I disappeared,",
      "When we needed it the most,",
      "I couldn't hurt you any longer,",
      "There's no excuse, although I used,",
      "The last of my strength,",
      "Just to hold it together,",
      "I'm sorry, if..",
      "",
      "[Refrain]",
      "It hurts more than it helps,",
      "If only we can,",
      "",
      "[Chorus]",
      "I guess we'll never know,",
      "How would our love grow,",
      "I guess we'll never know,",
      "How we could get by, no,",
      "I can't get out of this misery,",
      "It's so much for me,",
      "And too much for you,",
      "But both could never throw,",
      "I guess we'll never know..",
      "Ohh.. we'll never know..",
      "",
      "[Verse 1]",
      "I'm sorry when,",
      "I got used to it,",
      "You needed me to be strong,",
      "I did, but I did so wrong,",
      "Not knowing, I was coping,",
      "And I was hoping,",
      "To hold you longer,",
      "I'm sorry, if..",
      "",
      "[Refrain]",
      "It hurts more than it helps,",
      "If only we can,",
      "",
      "[Chorus]",
      "I guess we'll never know,",
      "How would our love grow,",
      "I guess we'll never know,",
      "How we could get by, no,",
      "I can't get out of this misery,",
      "It's so much for me,",
      "And too much for you,",
      "But both could never throw,",
      "I guess we'll never know..",
      "Ohh.. we'll never know..",
      "",
      "[Bridge]",
      "Our hearts we're broken from the start,",
      "All these lies, and the deceptions,",
      "We're breaking us apart,",
      "If we can be honest and forgive,",
      "Give more so we could live,",
      "Our lives not wanting more,",
      "We always wanted more..",
      "",
      "[Chorus]",
      "I guess we'll never know,",
      "How would our love grow...",
      "",
      "[Chorus higher key]",
      "I guess we'll never know,",
      "How would our love grow,",
      "I guess we'll never know,",
      "How we could get by, no,",
      "I can't get out of this misery,",
      "It's so much for me,",
      "And too much for you,",
      "But both could never throw,",
      "",
      "I guess we'll never know..",
      "Ohh.. we'll never know..",
      "",
      "[Hook]",
      "La, la, la..",
      "La, la, la..",
      "La, la, la..",
      "La, la, la..",
      "",
      "I guess we'll never know..",
      "Ohh.. we'll never know..",
      "Ohh.."
    ]
  },
  {
    id: "jopay",
    title: "Jopay",
    artist: "3rd Harmonik",
    album: "Cover",
    cover: "/music/Jopay (Cover) - 3rd Harmonik.png",
    url: "/music/Jopay/Jopay (Cover) - 3rd Harmonik.mp3",
    duration: "3:40",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ec4899",
    funFacts: ["A high-energy cover of the Filipino classic.", "The band added their signature harmonic layers to the arrangement.", "Dadalhin kita sa aming bahay..."],
    lyrics: [
      "[Verse 1]",
      "Jopay, kamusta ka na?",
      "Palagi kitang pinapanood, nakikita",
      "Jopay, pasensya ka na",
      "Wala rin kasi akong makausap at kasama",
      "",
      "[Pre-Chorus]",
      "'Wag ka nang mawala ('Wag ka nang mawala)",
      "'Wag ka nang mawala ('Wag ka nang mawala)",
      "Ngayon",
      "",
      "[Chorus]",
      "Dadalhin kita sa aming bahay",
      "'Di tayo mag-aaway",
      "Aalis tayo sa tunay na mundo",
      "Dadalhin kita sa aming bahay",
      "'Di tayo mag-aaway",
      "Aalis tayo sa tunay na mundo",
      "",
      "[Verse 2]",
      "Jopay, kamusta na ba?",
      "Buti ka pa, palagi kang masaya",
      "Jopay, buti na lang",
      "Nariyan ka, hindi na ako nag-iisa",
      "",
      "[Pre-Chorus]",
      "'Wag ka nang mawala ('Wag ka nang mawala)",
      "'Wag ka nang mawala ('Wag ka nang mawala)",
      "Ngayon",
      "",
      "[Chorus]",
      "Dadalhin kita sa aming bahay",
      "'Di tayo mag-aaway",
      "Aalis tayo sa tunay na mundo",
      "Dadalhin kita sa aming bahay",
      "'Di tayo mag-aaway",
      "Aalis tayo sa tunay na mundo",
      "Sa tunay na mundo",
      "",
      "[Pre-Chorus]",
      "'Wag ka nang mawala ('Wag ka nang mawala)",
      "'Wag ka nang mawala ('Wag ka nang mawala)",
      "Ngayon",
      "",
      "[Chorus]",
      "Dadalhin kita sa aming bahay",
      "'Di tayo mag-aaway",
      "Aalis tayo sa tunay na mundo",
      "Dadalhin kita sa aming bahay",
      "'Di tayo mag-aaway",
      "Aalis tayo sa tunay na mundo",
      "Sa tunay na mundo"
    ]
  },
  {
    id: "kailan-sinta",
    title: "Kailan, Sinta",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Kailan, Sinta/Kailan, Sinta.mp3",
    duration: "4:00",
    playCount: 0,
    isFavorite: false,
    accentColor: "#10b981",
    funFacts: ["A song about watching someone you love get hurt by others.", "Wait for the moment when they notice the one who truly cares.", "The 'pusong bato' refers to those who don't appreciate love."],
    lyrics: [
      "Kailan, Sinta? - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Mata mo'y laging sa iba nakatuon",
      "'Di man lang mapansin, ako'y naririto ngayon",
      "Bawat ngiti ko, bawat alay na pansin",
      "Parang hangin lang, sa'yo'y dumadaan din",
      "",
      "Nakikita ko, ang sakit sa 'yong tingin",
      "Kapag ika'y iniwan, luha'y 'di mapigilan",
      "Paulit-ulit na lang, eksenang kay pait",
      "Bakit ba sa kanila, puso mo'y kumakapit?",
      "",
      "[Pre-Chorus]",
      "Isang bulong na lang, sana'y iyong marinig",
      "Ang pusong ito, sa'yo lang umiibig",
      "Ngunit 'di mo alam, o sadyang nagbubulag-bulagan?",
      "",
      "[Chorus]",
      "Hindi mo ba nakikita, ang pag-ibig kong laan?",
      "Laging narito, sa'yong tabi, nag-aabang",
      "Habang ika'y lumuluha, sa piling ng iba",
      "Sila'y panandalian, ako'y nandito, sinta",
      "Oh, kailan mo ba mapapansin, itong aking damdamin?",
      "",
      "[Verse 2]",
      "Sinubukan ko nang lumayo, iwasan ka",
      "Pero paano, kung ikaw ang laging hanap-hanap pa?",
      "Kahit 'di mo masabi, na ako'y kaibigan man lang",
      "Sa anino mo'y kuntento, kahit nasasaktan",
      "",
      "[Pre-Chorus]",
      "Isang sulyap mo lang, sana'y mapunta sa akin",
      "Ang pusong ito, pagod nang manalangin",
      "Ngunit 'di mo alam, o sadyang nagbubulag-bulagan?",
      "",
      "[Chorus]",
      "Hindi mo ba nakikita, ang pag-ibig kong laan?",
      "Laging narito, sa'yong tabi, nag-aabang",
      "Habang ika'y lumuluha, sa piling ng iba",
      "Sila'y panandalian, ako'y nandito, sinta",
      "Oh, kailan mo ba mapapansin, itong aking damdamin?",
      "",
      "[Bridge]",
      "Bakit ba sila pa rin ang iyong pinipili?",
      "Mga pusong bato, walang tunay na silbi",
      "Kung bubuksan mo lang, ang 'yong mga mata",
      "Makikita mong ako, ang tunay na nagmamahal sa'yo, sinta",
      "",
      "[Final]",
      "Hindi mo ba nakikita, ang pag-ibig kong laan?",
      "Laging narito, sa'yong tabi, nag-aabang",
      "Habang ika'y lumuluha, sa piling ng iba",
      "Sila'y panandalian, ako'y nandito, sinta",
      "Oh, kailan mo ba mapapansin, itong aking damdamin?",
      "",
      "[Outro]",
      "Kailan, sinta?...",
      "Hindi mo ba nakikita?...",
      "Narito lang ako..."
    ]
  },
  {
    id: "kometa",
    title: "Kometa",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "/music/Kometa/Cover.png",
    url: "/music/Kometa/Kometa - 3rd Harmonik.mp3",
    duration: "4:15",
    playCount: 0,
    isFavorite: false,
    accentColor: "#f59e0b",
    funFacts: ["Uses the metaphor of a comet for a fleeting, bright love.", "Features atmospheric synth layers and driving drums.", "Captured in a moment of cosmic inspiration."],
    lyrics: [
      "Kometa - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Hanap-hanap ko parin,",
      "Bituin nagnining-ning,",
      "Habang ako'y nakikinig,",
      "Sa lamig ng iyong tinig,",
      "Oh, tila ba isang minuto,",
      "Lang ang nakalipas at,",
      "Biglang umaga na pala,",
      "Tapos isang minuto pa,",
      "Ay abot takipsilim na..",
      "",
      "[Pre-chorus]",
      "Kay bigat ng paa,",
      "Kay gaan ng pakiramdam,",
      "Sa iyong tabi lang ang,",
      "Puso ko gustong mawala..",
      "",
      "[Chorus]",
      "Parang isang kometa,",
      "Parang isang iglap ka lang,",
      "Isang kisap mata,",
      "Ang yakap mo madarama,",
      "Oh, kay liwanag mo mahal,",
      "Sinusundan ng mga mata,",
      "Kung saan-saan ako mapunta,",
      "Sa'yo babagsak, aking kometa..",
      "Aking kometa..",
      "",
      "[Verse 2]",
      "Mundo ko'y nag-iiba, kulay biglang sumisigla",
      "Bawat ordinaryo, sa'yo'y nagiging mahika",
      "Ang dating gabi kong madilim, ngayo'y may talang gabay",
      "Sa 'yong liwanag, ang anino ko'y sumasabay",
      "",
      "[Pre-chorus]",
      "Kay bigat ng paa,",
      "Kay gaan ng pakiramdam,",
      "Sa iyong tabi lang ang,",
      "Puso ko gustong mawala..",
      "",
      "[Chorus]",
      "Parang isang kometa,",
      "Parang isang iglap ka lang,",
      "Isang kisap mata,",
      "Ang yakap mo madarama,",
      "Oh, kay liwanag mo mahal,",
      "Sinusundan ng mga mata,",
      "Kung saan-saan ako mapunta,",
      "Sa'yo babagsak, aking kometa..",
      "Aking kometa..",
      "",
      "[Bridge]",
      "Dalhin man ng agos, sa kalawakan ng pag-ibig",
      "Puso'y laan sa'yo, walang alinlangan, sinta",
      "Ikaw ang uniberso, bituin kong nagniningning",
      "Sa'yo ang aking mundo, tadhanang 'di magmamaliw.",
      "",
      "[Final]",
      "Parang isang kometa,",
      "Parang isang iglap ka lang,",
      "Isang kisap mata,",
      "Ang yakap mo madarama,",
      "Oh, kay liwanag mo mahal,",
      "Sinusundan ng mga mata,",
      "Kung saan-saan ako mapunta,",
      "Sa'yo babagsak, aking kometa..",
      "Aking kometa..",
      "Aking kometa..",
      "Aking kometa..",
      "Aking kometa.."
    ]
  },
  {
    id: "love",
    title: "Love",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Love/Love - 3rd Harmonik.mp3",
    duration: "3:52",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ef4444",
    funFacts: ["A philosophical take on what love is—'defies logic'.", "Explains that love is like 'losing a winning game'.", "Features the line: 'Twice on Sundays, ten out of ten'."],
    lyrics: [
      "[Verse 1]",
      "What is love?",
      "Yeah, I'll tell you,",
      "Might sound clichè, mind you,",
      "Here's the thing, listen..",
      "You don't get to choose,",
      "Because love chooses,",
      "Defies logic. One loses,",
      "Their minds over it, to get over it.",
      "",
      "[Refrain]",
      "It's like you're losing a winning game,",
      "But that's no shame..",
      "",
      "[Chorus]",
      "In other words, in other worlds,",
      "I'd still choose you, over and over,",
      "Twice on Sundays, ten out of ten,",
      "Ohh.. don't need to pretend,",
      "That in other words, I love you,",
      "And in other worlds, I'll tell you,",
      "It won't be easy to forget,",
      "'Coz I'll be having no regrets,",
      "Ohh.. love.",
      "",
      "[Verse 2]",
      "How to love?",
      "Yeah, I'll tell you,",
      "Might sound corny, mind you,",
      "I know I sound overdramatic,",
      "But there's no perfect,",
      "You just gotta do,",
      "What you have to do. Nothing cryptic,",
      "Don't overcomplicate the already complicated.",
      "",
      "[Refrain]",
      "Ohh.. It's like you're losing a winning game,",
      "But that's no shame, 'coz..",
      "",
      "[Chorus]",
      "In other words, in other worlds,",
      "I'd still choose you, over and over,",
      "Twice on Sundays, ten out of ten,",
      "Ohh.. don't need to pretend,",
      "That in other words, I love you,",
      "And in other worlds, I'll tell you,",
      "It won't be easy to forget,",
      "'Coz I'll be having no regrets,",
      "Ohh.. love..",
      "Ohh.. love..",
      "",
      "[Bridge]",
      "If you find yourself in a pinch,",
      "Don't you ever regret,",
      "You'll learn the most from the toughest lessons,",
      "And if you ever find yourself back to square one,",
      "Well.. don't stop. \"You know what to do now, right??\"",
      "",
      "[Chorus]",
      "In other words, in other worlds,",
      "I'd still choose you, over and over,",
      "Twice on Sundays, ten out of ten,",
      "Ohh.. don't need to pretend...",
      "",
      "[Chorus]",
      "In other words, in other worlds,",
      "I'd still choose you, over and over,",
      "Twice on Sundays, ten out of ten,",
      "Ohh.. don't need to pretend,",
      "That in other words, I love you,",
      "And in other worlds, I'll tell you,",
      "It won't be easy to forget,",
      "'Coz I'll be having no regrets,",
      "Ohh.. love,",
      "Ohh.. love,",
      "Ohh.. love,",
      "Ohh.. is this what love is?",
      "Ohh.. love.."
    ]
  },
  {
    id: "makulimlim",
    title: "Makulimlim",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Makulimlim/Makulimlim - 3rd Harmonik.mp3",
    duration: "4:12",
    playCount: 0,
    isFavorite: false,
    accentColor: "#6366f1",
    funFacts: ["Describes a world as overcast and gloomy as the weather.", "The 'kapos na larawan' represents incomplete memories.", "A journey from the old 'self' to the new 'self' after pain."],
    lyrics: [
      "Makulimlim - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Naglalakad sa dilim,",
      "Nagbabakasakali ding,",
      "May makapansin,",
      "Aking mundo'y makulimlim,",
      "Pumapatuloy ang agos ng oras,",
      "Tinataboy ang nakaraan, ika'y luhaan,",
      "Ikay nasaktan, at nauwing duguan,",
      "Gustong itapon ang kapos na larawan,",
      "",
      "[Refrain]",
      "Hindi ka bilanggo,",
      "Ito din ay maglalaho..",
      "",
      "[Chorus]",
      "Kay bigat ng damdamin,",
      "Kasingbigat ng papatak na ulan,",
      "Sa gitna ng kawalan,",
      "Makulimlim ang aking mundo,",
      "Kay hirap pala taposin,",
      "Kahit tapos na, pero sige na,",
      "Kahit mahirap, parang pangarap,",
      "Makulimlim ang aking mundo..",
      "Ohh..",
      "",
      "[Verse 2]",
      "Tinatanaw bagong umaga,",
      "Nag-uumpisa sa wala,",
      "Pero nakakapagtaka,",
      "Naubusan na nga ba?",
      "Malayo ang tanaw, pero nakatitig",
      "Sa dating ako,",
      "Sa bagong ako..",
      "",
      "[Refrain]",
      "Hindi ka bilanggo,",
      "Ito din ay maglalaho..",
      "",
      "[Chorus]",
      "Kay bigat ng damdamin,",
      "Kasingbigat ng papatak na ulan,",
      "Sa gitna ng kawalan,",
      "Makulimlim ang aking mundo,",
      "Kay hirap pala taposin,",
      "Kahit tapos na, pero sige na,",
      "Kahit mahirap, parang pangarap,",
      "Makulimlim ang aking mundo..",
      "Ohh..",
      "",
      "[Bridge]",
      "Ibang-iba ang kalangitan,",
      "Tila uulan,",
      "Tila babagsak,",
      "At tila ba uubosin..",
      "",
      "[Chorus]",
      "Kay bigat ng damdamin,",
      "Kasingbigat ng papatak na ulan,",
      "Sa gitna ng kawalan,",
      "Makulimlim ang aking mundo,",
      "Kay hirap pala taposin,",
      "Kahit tapos na, pero sige na,",
      "Kahit mahirap, parang pangarap,",
      "Makulimlim ang aking mundo..",
      "Ohh..",
      "",
      "Kay hirap pala taposin,",
      "Kahit tapos na, pero sige na,",
      "Kahit mahirap, parang pangarap,",
      "Makulimlim ang aking mundo..",
      "Ohh.."
    ]
  },
  {
    id: "my-beautiful-disaster",
    title: "My Beautiful Disaster",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/My Beautiful Disaster/My Beautiful Disaster - 3rd Harmonik.mp3",
    duration: "4:08",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ec4899",
    funFacts: ["A 'pretty mess' and 'so gangster'—an unconventional love song.", "Explores the risk of dreaming big and falling hard.", "Features Aljay's signature colorful songwriting style."],
    lyrics: [
      "My Beautiful Disaster - 3rd Harmonik",
      "",
      "[Verse 1]",
      "I didn't think it would end this way,",
      "My hopeful mind, it's beginning to sway,",
      "I came across a,",
      "Beautiful disaster, a pretty mess, oh, so gangster,",
      "I didn't think that we would start it off,",
      "A simple glance, and when you look my way,",
      "I feel like it's,",
      "A heavy-hitting blaster, it's not a miss, oh, please don't stare..",
      "",
      "[Refrain]",
      "Found myself in a swirl,",
      "And, you know what?",
      "",
      "[Chorus]",
      "Never will I,",
      "Ever will,",
      "Forever, should,",
      "I ever think,",
      "Of disgracing myself, by saying that,",
      "It's all too easy, just by loving you,",
      "I never should, or ever would,",
      "Be hoping that,",
      "You will look easily,",
      "Because you,",
      "You're extra special, you..",
      "",
      "[Verse 2]",
      "I always hoped it would end this way,",
      "Oh.. my colorful mind, it's beginning to dream,",
      "I came across a,",
      "Beautiful disaster, a neverending kiss, yeah, she's so gangster,",
      "I always hoped that I could talk to you,",
      "A simple conversation.. don't mind my admiration,",
      "'Coz for sure, it's,",
      "Truly something different, it's what I meant, oh, how it would go..",
      "",
      "[Refrain]",
      "Found myself in a swirl,",
      "And, you know what?",
      "",
      "[Chorus]",
      "Never will I,",
      "Ever will,",
      "Forever, should,",
      "I ever think,",
      "Of disgracing myself, by saying that,",
      "It's all too easy, just by loving you,",
      "I never should, or ever would,",
      "Be hoping that,",
      "You will look easily,",
      "Because you,",
      "You're extra special, you..",
      "",
      "[Bridge]",
      "A beautiful disaster,",
      "It's always more painful to fall,",
      "If your dreams are this tall,",
      "A hope for everafter,",
      "It's more difficult in here,",
      "You don't wanna disappear..",
      "",
      "[Chorus]",
      "Never will I,",
      "Ever will,",
      "Forever, should,",
      "I ever think,",
      "Of disgracing myself, by saying that,",
      "It's all too easy, just by loving you,",
      "I never should, or ever would,",
      "Be hoping that,",
      "You will look easily,",
      "Because you,",
      "You're extra special, you..",
      "",
      "[Chorus]",
      "Never will I,",
      "Ever will,",
      "Forever, should,",
      "I ever think,",
      "Of disgracing myself, by saying that,",
      "It's all too easy, just by loving you,",
      "I never should, or ever would,",
      "Be hoping that,",
      "You will look easily,",
      "Because you,",
      "You're extra special, you..",
      "You're extra special, you..",
      "My beautiful disaster, you..",
      "My happy everafter, you.."
    ]
  },
  {
    id: "nandito",
    title: "Nandito",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Nandito/Nandito - 3rd Harmonik.mp3",
    duration: "3:56",
    playCount: 0,
    isFavorite: false,
    accentColor: "#10b981",
    funFacts: ["A comforting track for anyone feeling lost or unheard.", "Reminds the listener that 'many are standing right behind them'.", "Features the 'apoy ng puso' and 'kulo ng dugo' for emotional weight."],
    lyrics: [
      "Nandito - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Kanina lamang ay nakausap pa kita,",
      "Kay lalim ng isip, kay layo ng tingin,",
      "Kanina lamang may hindi sinasagot,",
      "Mga tanong, mga paano, mga bakit,",
      "Subalit paano ko maaayos ang lahat,",
      "Kung mismo ikaw ay hindi ko maabot,",
      "Nababagot, damdamin kay hilaw,",
      "Nakasimangot, naliligaw..",
      "",
      "[Refrain]",
      "Isang ngiti naman jan,",
      "Maaayos din yan,",
      "",
      "[Chorus]",
      "'Di mo lang alam,",
      "Gaano ka kahalaga,",
      "'Di mo lang alam, sinta,",
      "'Di mo din alam,",
      "Na andaming nasa likod mo lang,",
      "Hindi sa nag-aabang,",
      "Kundi nandito lang sila talaga,",
      "Nandito,",
      "Nandito para sa'yo..",
      "",
      "[Verse 2]",
      "Kahapon lamang ay tumatawa ka,",
      "Kay saya ng araw, kay sigla ng panahon,",
      "Kahapon lamang may mga sinasagot,",
      "Mga tanong, mga paano, mga bakit,",
      "",
      "[Refrain]",
      "Isang ngiti naman jan,",
      "Maaayos din yan,",
      "",
      "[Chorus]",
      "'Di mo lang alam,",
      "Gaano ka kahalaga,",
      "'Di mo lang alam, sinta,",
      "'Di mo din alam,",
      "Na andaming nasa likod mo lang,",
      "Hindi sa nag-aabang,",
      "Kundi nandito lang sila talaga,",
      "Nandito,",
      "Nandito para sa'yo..",
      "",
      "[Bridge]",
      "Kung alam mo lang,",
      "Kung maririnig mo,",
      "Ang apoy ng puso,",
      "Ang kulo ng dugo,",
      "Kapag ika'y nasasaktan,",
      "Hindi naiiwasang, masaktan din ako,",
      "Sapagkat nandito,",
      "Nandito lang ako..",
      "",
      "[Chorus]",
      "'Di mo lang alam,",
      "Gaano ka kahalaga,",
      "'Di mo lang alam, sinta,",
      "'Di mo din alam,",
      "Na andaming nasa likod mo lang,",
      "Hindi sa nag-aabang,",
      "Kundi nandito lang sila talaga,",
      "Nandito,",
      "Nandito para sa'yo..",
      "Nandito,",
      "Nandito para sa'yo..",
      "Nandito,",
      "Nandito para sa'yo.."
    ]
  },
  {
    id: "nobody-knows",
    title: "Nobody Knows",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Nobody Knows/Nobody Knows - 3rd Harmonik.mp3",
    duration: "4:22",
    playCount: 0,
    isFavorite: false,
    accentColor: "#8b5cf6",
    funFacts: ["A song about secret moments and shared destiny.", "The time 'just slows down' when eyes meet.", "Uses a 'Nah, nah, nah' outro to emphasize the unspoken."],
    lyrics: [
      "Nobody Knows - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Do you believe,",
      "In destiny?",
      "One melody,",
      "Is all you need,",
      "All too familiar,",
      "This rainy night,",
      "Hold on tight,",
      "You're safe with me..",
      "",
      "[Chorus]",
      "And time just slows down, ",
      "and nobody knows,",
      "Just, you and me,",
      "The way that our eyes,",
      "Meet, like they know,",
      "Each other from,",
      "A long time ago,",
      "And nobody knows,",
      "Just how this goes,",
      "Ohh.. nobody knows, yeah..",
      "Nobody knows..",
      "",
      "[Verse 2]",
      "Do you believe,",
      "In miracles?",
      "Just one day,",
      "Is all we need,",
      "Nothing similar,",
      "This cloudy day,",
      "Cold night ahead,",
      "You'll be safe with me..",
      "",
      "[Chorus]",
      "And time just slows down, ",
      "and nobody knows,",
      "Just, you and me,",
      "The way that our eyes,",
      "Meet, like they know,",
      "Each other from,",
      "A long time ago,",
      "And nobody knows,",
      "Just how this goes,",
      "Ohh.. nobody knows, yeah..",
      "Nobody knows..",
      "",
      "[Bridge]",
      "Nah, nah, nah, nah..",
      "Nobody knows..",
      "Nah, nah, nah, nah..",
      "Only you..",
      "",
      "And time just slows,",
      "Down, and nobody knows...",
      "",
      "[Chorus]",
      "And time just slows down, ",
      "and nobody knows,",
      "Just, you and me,",
      "The way that our eyes,",
      "Meet, like they know,",
      "Each other from,",
      "A long time ago,",
      "And nobody knows,",
      "Just how this goes,",
      "Ohh.. nobody knows, yeah..",
      "Nobody knows..",
      "",
      "[Final]",
      "And time just slows,",
      "Down, and nobody knows,",
      "Just, you and me,",
      "The way it flows,",
      "Just like no other,",
      "There is no other,",
      "It's you and me,",
      "And nobody knows,",
      "Just how this goes,",
      "Ohh.. nobody knows, yeah..",
      "Nobody knows..",
      "",
      "Nah, nah, nah, nah..",
      "Nobody knows..",
      "Nah, nah, nah, nah..",
      "Only you.."
    ]
  },
  {
    id: "pagtatapos",
    title: "Pagtatapos",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Pagtatapos/Pagtatapos - 3rd Harmonik.mp3",
    duration: "5:05",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ef4444",
    funFacts: ["A heavy-hitting track about the end of a long journey.", "Describes the 'luggage' of memories and the weight of the past.", "The bridge explores the loneliness of an era ending."],
    lyrics: [
      "Pagtatapos - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Wala nang pumapatak na luha, 'di na tulad ng dati,",
      "Tanging pagod na lang ang nararamdaman ng pusong sa'yo nagsilbi,",
      "Walang ginagawa pero bakit ganito? Para bang ako'y nabibigatan,",
      "'Di ko naman sinasadya, pero para bang 'di ko na kayang lumaban.",
      "",
      "Noong simula, matamis ang lahat, parang walang katapusan,",
      "Lahat ng nakikita natin, puno ng kulay at kasiyahan,",
      "Pero ngayon, kay dilim na ng daan, parang ang bagal ng oras,",
      "Para bang patungo sa wala, kung meron mang dulo, baka patungong labas.",
      "",
      "[Refrain]",
      "Ano, kaya pa ba?",
      "Ano, kaya pa ba?",
      "",
      "[Chorus]",
      "Pipilitin pa ba ang puso,",
      "Kapag ito na ay sumusuko?",
      "Hindi ko na kaya pang magkunwari pa,",
      "Na ako'y 'di nasasaktan,",
      "Pipiliin pa bang mabigo muli?",
      "Kapag alam mo na anong huli?",
      "'Wag na tayong magbiroan,",
      "Ayoko nang umasa, ayoko nang maniwala,",
      "Kahit ayaw kong mawala ka..",
      "",
      "[Verse 2]",
      "Dati mong sandalan, ngayo’y pasan ko na parang pabigat,",
      "Wala namang sugat pero bakit ang sakit, parang may pilat,",
      "Naka-ukit sa alaala na dati'y puno ng pag-asa,",
      "Ngunit ngayon, para bang iniwan na lang sa gitna ng wala.",
      "",
      "Lahat ng pinaniwalaan natin, bigla na lang naparam,",
      "Akala ko panghabambuhay, pero ba't parang pinaglalaruan ng tadhana lang?",
      "Sino’ng mag-aakalang ganito lang kabilis mabura?",
      "Sino’ng mag-aakalang tayo’y babagsak nang ganito kabilis mawala?",
      "",
      "Dati ang dali mong kausap, kahit anong oras, kahit anong bagay,",
      "Ngayon, ni kamustahin ka, hindi ko na magawa, hindi ko na mahanap ang dating ikaw,",
      "Pinipilit kong ngumiti, pero para bang hindi ko na kaya,",
      "Masakit isipin na tayo’y nagkasama, pero ngayon, parang wala nang halaga.",
      "",
      "[Refrain]",
      "Ano, kaya pa ba?",
      "'Lam nating ang hirap na...",
      "",
      "[Chorus]",
      "Pipilitin pa ba ang puso,",
      "Kapag ito na ay sumusuko?",
      "Hindi ko na kaya pang magkunwari pa,",
      "Na ako'y 'di nasasaktan,",
      "Pipiliin pa bang mabigo muli?",
      "Kapag alam mo na anong huli?",
      "'Wag na tayong magbiroan,",
      "Ayoko nang umasa, ayoko nang maniwala,",
      "Kahit ayaw kong mawala ka..",
      "",
      "[Bridge]",
      "Pinakamahirap magsimula kung 'di mo alam kung saan patungo,",
      "Para bang sinusubukan mong buuin ang kwento na wala nang dulo,",
      "Pa’no kung ito na ‘yon? Pa’no kung wala na talagang kasunod?",
      "Para bang iniwan tayong dalawa sa ere, 'di na natin mabuo ang buhol.",
      "",
      "Saan na tayo dadalhin ng ganitong damdamin?",
      "Tayo ba’y magpapatuloy o ito na ang ating hangin?",
      "Alam kong mahirap, pero 'di ko na kaya,",
      "Mas pipiliin ko nang lumaya kaysa manatili sa sakit na wala nang halaga.",
      "",
      "[Chorus]",
      "Pipilitin pa ba ang puso,",
      "Kapag ito na ay sumusuko?",
      "Hindi ko na kaya pang magkunwari pa,",
      "Na ako'y 'di nasasaktan,",
      "Pipiliin pa bang mabigo muli?",
      "Kapag alam mo na anong huli?",
      "'Wag na tayong magbiroan,",
      "Ayoko nang umasa, ayoko nang maniwala,",
      "Kahit ayaw kong mawala ka..",
      "",
      "[Outro]",
      "Kahit ayaw ko,",
      "Kung ayaw mo,",
      "Tama na,",
      "Tama ka..",
      "Kahit ayaw ko,",
      "Kung ayaw mo,",
      "Tama na,",
      "Tama ka.."
    ]
  },
  {
    id: "pahina",
    title: "Pahina",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Pahina/Pahina - 3rd Harmonik.mp3",
    duration: "4:48",
    playCount: 0,
    isFavorite: false,
    accentColor: "#f59e0b",
    funFacts: ["A narrative song that uses 'pages' of a book as a metaphor.", "Features a raw rap section exploring the 'silence of the night'.", "The title means 'page', representing a chapter in life."],
    lyrics: [
      "Pahina - 3rd Harmonik",
      "",
      "[Intro]",
      "Hmmm.. ohhh...",
      "Hmmmmm..",
      "",
      "[Verse 1]",
      "Dati ay naghihintay,",
      "Nag-aabang sa wala,",
      "Na para bang naa-abala,",
      "Nakatitig kahit saan,",
      "Kahit saan nalang napupunta,",
      "Naguguluhan kong isipan..",
      "",
      "Sa tuwing naa-alala ko mga lumipas na araw,",
      "Mapaglaro nga talaga ang panahon, tinutulak kahit na ayaw,",
      "Pero 'di ko naman maipagkakait,",
      "Kung ang tadhana ay papalapit,",
      "",
      "[Rap]",
      "Kung ang kilos ko’y parang kuliglig sa dilim ng aliwan,",
      "Tahimik pero gumugulo sa isip ng hindi alam.",
      "Guhit ng palad, pilit kong binabasa nang pabaliktad,",
      "Baka sakaling makuha ko kung bakit ako ang nadilat.",
      "",
      "Kandado ang salitang ‘di mo maririnig sa bukambibig,",
      "Kahit binigkas na—parang lihim pa rin sa panaginip.",
      "Pagod ang tinig, pero hindi pa rin tinatalikuran,",
      "Ang pag-ikot ng silab—mga salitang walang kaligtasan.",
      "",
      "[Pre-chorus]",
      "Dumating ang isang kaluluwa,",
      "'Di hamak na kay ganda ng mga mata,",
      "Kasing ganda ng kanyang ngiti,",
      "Pati ako tuloy nabibighani,",
      "",
      "[Chorus]",
      "Ohh, patawad kung hindi ko nasabi,",
      "Ang mga dapat kong sinabi,",
      "Nung ako pa'y isang walang alam,",
      "Walang kamuwang-muwang,",
      "Hindi ko man lang,",
      "Oh, 'di ko man lang,",
      "Naamin sayo, biglang nalilito,",
      "Hindi ito ang dulo,",
      "Patawad.. minahal kita,",
      "Noon - hanggang ngayon..",
      "",
      "[Verse 2 – Rap]",
      "Sa pagitan ng gabi at ng ala-ala,",
      "Doon ako laging napapadpad, tila ba wala nang pabalik.",
      "Hawak ang mga salitang ‘di mo kailanman narinig,",
      "Pinipiga sa puso, pero ‘di mailabas sa bibig.",
      "",
      "Tumatakbo sa oras na hindi ko mahabol,",
      "Parang aninong humahagibis sa likod ng alon.",
      "Pinili mong lumakad sa liwanag,",
      "Ako’y naiwan sa dilim—bitbit ang bawat panaghoy at saglit.",
      "",
      "'Di ako bayani sa kwento mong buo na,",
      "Ako 'yung pahina'ng laging nababalewala.",
      "Pero kahit wasak, sinusulat pa rin kita,",
      "Sa tulang ‘di ko kayang tapusin, kahit alam kong wala ka na.",
      "",
      "[Pre-chorus]",
      "Dumating ang isang kaluluwa,",
      "'Di hamak na kay ganda ng mga mata,",
      "Kasing ganda ng kanyang ngiti,",
      "Pati ako tuloy nabibighani,",
      "",
      "[Chorus]",
      "Ohh, patawad kung hindi ko nasabi,",
      "Ang mga dapat kong sinabi,",
      "Nung ako pa'y isang walang alam,",
      "Walang kamuwang-muwang,",
      "Hindi ko man lang,",
      "Oh, 'di ko man lang,",
      "Naamin sayo, biglang nalilito,",
      "Hindi ito ang dulo,",
      "Patawad.. minahal kita,",
      "Noon - hanggang ngayon..",
      "",
      "[Hook]",
      "[Pre-chorus]",
      "Dumating ang isang kaluluwa,",
      "'Di hamak na kay ganda ng mga mata,",
      "Kasing ganda ng kanyang ngiti,",
      "Pati ako tuloy nabibighani,",
      "",
      "[Chorus]",
      "Ohh, patawad kung hindi ko nasabi,",
      "Ang mga dapat kong sinabi,",
      "Nung ako pa'y isang walang alam,",
      "Walang kamuwang-muwang,",
      "Hindi ko man lang,",
      "Oh, 'di ko man lang,",
      "Naamin sayo, biglang nalilito,",
      "Hindi ito ang dulo,",
      "Patawad.. minahal kita,",
      "Noon - hanggang ngayon..",
      "",
      "[Outro]",
      "Pahina nang pahina ang paghinga, pero ngayo'y nag-iiba kasi iba ka nga,",
      "Sa huling yugto ako ang magdudulot ng saya't ganda, pero hindi kontento sa kwento, ako ang elemento,",
      "Na syang magpapahiwatig..",
      "Na may kasunod pang pahina."
    ]
  },
  {
    id: "perfect-time",
    title: "Perfect Time",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Perfect Time/Perfect Time - 3rd Harmonik.mp3",
    duration: "3:58",
    playCount: 0,
    isFavorite: false,
    accentColor: "#6366f1",
    funFacts: ["Written on a Sunday afternoon while listening to the radio.", "Captures the tension of waiting for a message that never comes.", "Explores the 'dramatic' nature of long-distance communication."],
    lyrics: [
      "Perfect Time - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Staring all day at the cieling,",
      "Remembering all the lingering pain,",
      "I still read the conversations,",
      "Where we were so curious, and you were so mysterious,",
      "",
      "The time is perfect,",
      "It's Sunday, and I hear our songs on the radio,",
      "Almost fell asleep,",
      "Thinking about this way too deep.",
      "",
      "[Refrain]",
      "What I would give just to have it with you,",
      "What I would give just to be with you..",
      "",
      "[Chorus]",
      "Oh.. one day we'll know,",
      "Someday it will show,",
      "No need to rush, let it ride,",
      "Don't let it die, let it fly,",
      "'Coz all we need is trust,",
      "That's all we need tonight,",
      "Ohh.. tonight,",
      "All we need is,",
      "Ohh.. tonight..",
      "",
      "[Verse 2]",
      "Waiting all day for your message,",
      "Just thinking 'bout how things could have gone south,",
      "But I read the conversations,",
      "Where we were so dramatic, it's funny 'coz we always get by,",
      "Yeah.. we always get by, ohh..",
      "",
      "[Refrain]",
      "What I would give just to have it with you,",
      "What I would give just to be with you..",
      "",
      "[Chorus]",
      "Oh.. one day we'll know,",
      "Someday it will show,",
      "No need to rush, let it ride,",
      "Don't let it die, let it fly,",
      "'Coz all we need is trust,",
      "That's all we need tonight,",
      "Ohh.. tonight,",
      "All we need is,",
      "Ohh.. tonight..",
      "",
      "[Bridge]",
      "No one could ever, ever have,",
      "The things that they really, really want,",
      "But it's the perfect time to say,",
      "I need to hear you say,",
      "That I need you.. today, and tonight..",
      "Ohhh.. all we need is, tonight..",
      "Ohhh.. all we need is, tonight..",
      "",
      "[Chorus]",
      "Oh.. one day we'll know,",
      "Someday it will show,",
      "No need to rush, let it ride,",
      "Don't let it die, let it fly,",
      "'Coz all we need is trust,",
      "That's all we need tonight,",
      "Ohh.. tonight,",
      "All we need is,",
      "Ohh.. tonight..",
      "",
      "That's all we need tonight,",
      "Ohh.. tonight,",
      "All we need is,",
      "Ohh.. tonight.."
    ]
  },
  {
    id: "sa-ngalan-ng-pagibig",
    title: "Sa Ngalan Ng Pagibig",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "", // Will use fallback
    url: "/music/Sa Ngalan Ng Pagibig/Sa Ngalan Ng Pagibig - 3rd Harmonik (Acoustic).mp3",
    duration: "4:15",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ec4899",
    funFacts: ["A tribute to a classic anthem, delivered in the 3rd Harmonik style.", "Focuses on the endurance of love through 'forever'.", "Features emotional, soaring vocal performances."],
    lyrics: [
      "[Verse 1]",
      "Hanggang kailan ako maghihintay",
      "Na para bang wala nang papalit sa'yo?",
      "Nasa'n ka man, sigaw ng puso ko'y",
      "Ikaw hanggang ngayon, ooh-woah-oh",
      "",
      "[Pre-Chorus]",
      "Kung sana lamang ay nakita mo",
      "Ang lungkot sa'yong ngiti",
      "Isang umagang 'di ka nagbalik",
      "Gumising ka at nang makita mo",
      "Ang tamis ng sandali",
      "Ng kahapong 'di magbabalik",
      "",
      "[Chorus]",
      "Hanggang sa dulo ng ating walang hanggan",
      "Hanggang ang puso'y wala nang nararamdaman",
      "Kahit matapos ang magpakailanpaman",
      "Ako'y maghihintay sa ngalan ng pag-ibig",
      "",
      "[Verse 2]",
      "Hanggang kailan ako maghihintay",
      "Na para bang walang iba sa piling mo?",
      "Nasa'n ka man, sigaw ng puso ko",
      "Ay ang pangalan mo, ooh-woah-oh",
      "",
      "[Pre-Chorus]",
      "Kung sana lamang ay nakita mo",
      "Ang lungkot sa'yong ngiti",
      "Isang umagang 'di ka nagbalik",
      "Gumising ka at nang makita mo",
      "Ang tamis ng sandali",
      "Ng kahapong 'di magbabalik",
      "",
      "[Chorus]",
      "Hanggang sa dulo ng ating walang hanggan",
      "Hanggang ang puso'y wala nang nararamdaman",
      "Kahit matapos ang magpakailan pa man",
      "Ako'y maghihintay sa ngalan ng pag-ibig",
      "",
      "[Bridge]",
      "Hanggang kailan pa ba magtitiis?",
      "Nalunod na sa kaiisip",
      "Huling kapiling ka'y sa aking panaginip",
      "Ikaw mula noon",
      "Ikaw hanggang ngayon",
      "",
      "[Interlude]",
      "Hanggang sa dulo ng ating walang hanggan",
      "Hanggang ang puso'y wala nang maramdaman",
      "",
      "[Chorus]",
      "Hanggang sa dulo ng ating walang hanggan",
      "Hanggang ang puso'y wala nang naramdaman",
      "Kahit matapos ang magpakailan pa man",
      "Ako'y maghihintay sa ngalan ng pag-ibig",
      "Hanggang sa dulo ng ating walang hanggan (Ako'y maghihintay, ako'y maghihintay)",
      "Hanggang ang puso'y wala nang nararamdaman (Ako'y maghihintay sa ngalan ng pag-ibig)",
      "Kahit matapos ang magpakailan pa man (Ako'y maghihintay, ako'y maghihintay)",
      "Ako'y maghihintay sa ngalan ng pag-ibig mo"
    ]
  },
  {
    id: "titulo",
    title: "Titulo",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Titulo/Titulo - 3rd Harmonik.mp3",
    duration: "3:54",
    playCount: 0,
    isFavorite: false,
    accentColor: "#10b981",
    funFacts: ["The title is the summary—the person who represents the whole story.", "Reflects on how some people are destined to be the 'title' of our lives.", "The bridge asks if they will meet again when time plays its games."],
    lyrics: [
      "Titulo - 3rd Harmonik",
      "",
      "[Verse 1]",
      "Hindi ko matandaan, pero nararamdaman,",
      "Hindi lang ng puso't isipan,",
      "Hindi ko masabi, pagkat hindi sigurado,",
      "Sapat nga ba, na ikaw ang titulo?",
      "",
      "Alam kong ang daming,",
      "Mga tao sa mundo,",
      "Pero hindi malayo,",
      "Ang kutob ko sa'yo,",
      "",
      "[Refrain]",
      "Parang hindi matatapos,",
      "Hangga't hindi magtatagpo..",
      "",
      "[Chorus]",
      "Nakasulat ang lahat,",
      "Sa aklat ng aking puso,",
      "At ito'y nakabuklat,",
      "Para iyong basahin, at unawa-in,",
      "Sa bawat tuldok,",
      "Ay may ikaw at,",
      "Bawat pikit ng mga mata,",
      "Ikaw agad nakikita..",
      "Ikaw ang titulo..",
      "",
      "[Verse 2]",
      "Hindi kinalimutan, ng pusong lumaban,",
      "Kahit hindi mapatunayan,",
      "Higit pa sa oras, na mga lumipas,",
      "Sapat na siguro, na ikaw ang titulo.",
      "",
      "[Refrain]",
      "Parang hindi matatapos,",
      "Hangga't hindi magtatagpo..",
      "",
      "[Chorus]",
      "Nakasulat ang lahat,",
      "Sa aklat ng aking puso,",
      "At ito'y nakabuklat,",
      "Para iyong basahin, at unawa-in,",
      "Sa bawat tuldok,",
      "Ay may ikaw at,",
      "Bawat pikit ng mga mata,",
      "Ikaw agad nakikita..",
      "Ikaw ang titulo..",
      "",
      "[Bridge]",
      "Ipagtatagpo bang muli?",
      "Kung sakaling huli,",
      "Na ang lahat at,",
      "Hindi na maibabalik?",
      "Ito ba'y pagkakataon,",
      "Na tayo'y muling hahamon,",
      "Sa mapaglarong panahon?",
      "",
      "[Chorus]",
      "Nakasulat ang lahat,",
      "Sa aklat ng aking puso,",
      "At ito'y nakabuklat,",
      "Para iyong basahin, at unawa-in,",
      "Sa bawat tuldok,",
      "Ay may ikaw at,",
      "Bawat pikit ng mga mata,",
      "Ikaw agad nakikita..",
      "Ikaw ang titulo..",
      "",
      "[Chorus]",
      "Nakasulat ang lahat,",
      "Sa aklat ng aking puso,",
      "At ito'y nakabuklat,",
      "Para iyong basahin, at unawa-in,",
      "Sa bawat tuldok,",
      "Ay may ikaw at,",
      "Bawat pikit ng mga mata,",
      "Ikaw agad nakikita..",
      "Ikaw ang titulo..",
      "Bawat pikit ng mga mata,",
      "Ikaw agad nakikita..",
      "Ikaw ang titulo..",
      "Ikaw ang titulo.."
    ]
  },
  {
    id: "totoo",
    title: "Totoo",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Totoo/Totoo (Acoustic) - 3rd Harmonik.mp3",
    duration: "4:02",
    playCount: 0,
    isFavorite: false,
    accentColor: "#f59e0b",
    funFacts: ["Captures a shared walk down a wet street after hours.", "The gate closing represents a final moment of intimacy.", "A declaration that some feelings are simply undeniable and 'true'."],
    lyrics: [
      "Totoo",
      "",
      "[Verse 1]",
      "Walang kapantay, ito ang pinaka",
      "Pinakamagandang araw sa aking gunita",
      "Stereo'y tumutunog, ramdam ang musika",
      "Kasabay ng tibok ng pusong namimiss ka",
      "",
      "Mahinang ilaw, bumabagay sa gabi",
      "Bawat saglit, parang ayaw ko nang umuwi",
      "Amoy ng buhok mo, iniikot sa daliri",
      "Nakakahalina, parang panaginip muli",
      "",
      "[Pre-chorus]",
      "Oras sa orasan, ‘di natin napansin",
      "Nang ako'y ma-mulat, huli na pala ang dating",
      "Naglalakad magkasabay sa basang kalsada",
      "Hanggang sa harap ng gate na nakasarado na",
      "",
      "[Chorus]",
      "Kaya't nilampasan ko ang lahat, at pinapasok kita",
      "Sa mundo kong ikaw ang sentro, mayayakap kita",
      "Walang katumbas bawat galaw, tila ‘di bibitaw",
      "At nang hinagkan mo ako, tunay ang nadama",
      "",
      "[Post-chorus]",
      "Alam kong iyun ay totoo",
      "Iyun ay totoo, oo",
      "Alam kong iyun ay totoo",
      "Iyun ay totoo, oo",
      "",
      "[Verse 2]",
      "Hatinggabi, malamig pero di ko ramdam",
      "Sa yakap mo pa lang, ako’y naliligayahan",
      "Tahimik ang paligid, pero tayong dal’wa",
      "Parang may sariling mundo na nilikha",
      "",
      "Mga mata mong nagsasabing ‘di ka aalis",
      "Parang eksena sa pelikulang matamis",
      "Lahat ng sandali, parang bumabagal",
      "Ayokong matapos, ayokong magpaalam",
      "",
      "[Pre-chorus]",
      "Oras sa orasan, ‘di natin napansin",
      "Nang ako'y ma-mulat, huli na pala ang dating",
      "Naglalakad magkasabay sa basang kalsada",
      "Hanggang sa harap ng gate na nakasarado na",
      "",
      "[Chorus]",
      "Kaya't nilampasan ko ang lahat, at pinapasok kita",
      "Sa mundo kong ikaw ang sentro, mayayakap kita",
      "Walang katumbas bawat galaw, tila ‘di bibitaw",
      "At nang hinagkan mo ako, tunay ang nadama",
      "",
      "[Bridge]",
      "Kung ako'y babalik sa panahon",
      "Paulit-ulit ka paring pipiliin",
      "Dahil sa puso ko, walang alinlangan",
      "Lahat ng nangyari,",
      "Lahat ng pagmamay-ari,",
      "I-aalay ko sa'yo (Ohhh..)",
      "",
      "[Final]",
      "Kaya't nilampasan ko ang lahat, at pinapasok kita (pinapasok kita)",
      "Sa mundo kong ikaw ang sentro, ikaw ang totoo  (ikaw ang totoo)",
      "Walang katumbas bawat segundo, tila ‘di matatapos  ('di matatapos)",
      "At nang hinagkan mo ako, iyun ay totoo",
      "",
      "[Outro]",
      "Alam kong iyun ay totoo",
      "Iyun ay totoo, oo",
      "Alam kong iyun ay totoo",
      "Iyun ay totoo, oo"
    ]
  },
  {
    id: "undo",
    title: "Undo",
    artist: "3rd Harmonik",
    album: "Single",
    cover: "",
    url: "/music/Undo/Undo - 3rd Harmonik (2025).mp3",
    duration: "4:05",
    playCount: 0,
    isFavorite: false,
    accentColor: "#ef4444",
    funFacts: ["A song about the regret of things that can't be taken back.", "The line 'Why was I too late?' echoes throughout the track.", "A raw performance about learning tough lessons from broken pieces."],
    lyrics: [
      "Undo - 3rd Harmonik",
      "",
      "Ohh..",
      "",
      "[Verse 1]",
      "I don't have much to say,",
      "You're leaving anyway,",
      "What can I do to make you stay?",
      "Don't know when's the right time and this broken heart of mine,",
      "Is bleeding so much that I can't undo what's done,",
      "",
      "[Pre-chorus]",
      "I do apologize,",
      "You know I realize,",
      "",
      "[Chorus]",
      "You walked out of my life,",
      "If I can just make it right,",
      "But what is it to fight when it's all in broken pieces?",
      "And the pain, it hurts just like a knife,",
      "If I can just hold you tight,",
      "I will hold you till forever,",
      "..why am I too late? Ohh..",
      "Why was I too late?",
      "Why was I too late?",
      "",
      "[Verse 2]",
      "What's done is done,",
      "You're leaving anyway,",
      "What can I do to change the way, that I said the things that make you think that I don't care?",
      "I have learned so much,",
      "And I can't undo what's done..",
      "",
      "[Chorus]",
      "You walked out of my life,",
      "If I can just make it right,",
      "But what is it to fight when it's all in broken pieces?",
      "And the pain, it hurts just like a knife,",
      "If I can just hold you tight,",
      "I will hold you till forever,",
      "..why am I too late? Ohh..",
      "Why was I too late?",
      "Why was I too late?",
      "",
      "[Chorus 2]",
      "You walked out of my life,",
      "If I can just make it right,",
      "But what is it to fight when it's all in broken pieces?",
      "And the pain, it hurts just like a knife,",
      "If I can just hold you tight,",
      "I will hold you till forever,",
      "..why am I too late? Ohh..",
      "Why was I too late?",
      "Why was I too late?",
      "",
      "[Final]",
      "You walked out of my life,",
      "If I can just make it right,",
      "But what is it to fight when it's all in broken pieces?",
      "And the pain, it hurts just like a knife,",
      "If I can just hold you tight,",
      "I will hold you till forever,",
      "..why am I too late? Ohh..",
      "Why was I too late?",
      "Why was I too late?"
    ]
  }
];

// Sort songs based on SONG_ORDER
export const INITIAL_SONGS: Song[] = _UNSORTED_SONGS.sort((a, b) => {
  const indexA = SONG_ORDER.indexOf(a.id);
  const indexB = SONG_ORDER.indexOf(b.id);
  // Songs not in SONG_ORDER go to the end
  const orderA = indexA === -1 ? SONG_ORDER.length : indexA;
  const orderB = indexB === -1 ? SONG_ORDER.length : indexB;
  return orderA - orderB;
});
